# Generated by Django 5.1 on 2024-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pixora", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagerequest",
            name="status",
            field=models.CharField(default="completed", max_length=50),
        ),
    ]
