# Generated by Django 5.1 on 2024-09-01 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pixora", "0002_imagerequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagerequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
